# hypercorn.toml
bind = ["127.1.1.0:8000"]
alpn_protocols = ["h3", "h2", "http/1.1"]  # Включаем поддержку HTTP/3
quic_bind = ["127.1.1.0:8000"]  # Добавляем поддержку QUIC
access_log = "-"  # Вывод логов доступа в консоль
error_log = "-"   # Вывод логов ошибок в консоль