"""add disabled column to users

Revision ID: 3781dcaa6b81
Revises: 
Create Date: 2024-07-08 00:41:43.324855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3781dcaa6b81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_id', table_name='articles')
    op.drop_index('ix_articles_title', table_name='articles')
    op.drop_table('articles')
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.drop_index('ix_users_full_name', table_name='users')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_users_full_name', 'users', ['full_name'], unique=False)
    op.drop_column('users', 'disabled')
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='articles_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='articles_pkey')
    )
    op.create_index('ix_articles_title', 'articles', ['title'], unique=False)
    op.create_index('ix_articles_id', 'articles', ['id'], unique=False)
    # ### end Alembic commands ###
